// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0, demoIndex as dmi0 } from '/Users/thienvu/Documents/Projects/Community/designable/docs/migration-v2.md?type=frontmatter';

export const filesMeta = {
  'docs/migration-v2': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/thienvu/Documents/Projects/Community/designable/docs/migration-v2.md?type=text'),
  },
}


export { tabs as tabsMeta } from './tabs';
