// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/migration-v2":{"path":"migration-v2","id":"docs/migration-v2","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/thienvu/Documents/Projects/Community/designable/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/thienvu/Documents/Projects/Community/designable/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/thienvu/Documents/Projects/Community/designable/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/migration-v2': React.lazy(() => import(/* webpackChunkName: "docs__migration-v2.md" */'/Users/thienvu/Documents/Projects/Community/designable/docs/migration-v2.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/thienvu/Documents/Projects/Community/designable/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
