// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/thienvu/Documents/Projects/Community/designable/node_modules/dumi/theme-default/slots/Hero/index.js';
